version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "6666:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  auth-microservice:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: auth-microservice
    ports:
      - "8090:8090"
    env_file:
      - .env.docker
    depends_on:
      - postgresql
    entrypoint: ["/bin/sh", "-c", "sleep 10 && uv run auth_microservice/src/create_db.py"]
